"""
Render a matched-jobs payload into an HTML email body + a PDF attachment.

HTML is the primary deliverable (rich, clickable, lands in the inbox); the PDF is
a portable archive copy. Both come from the same payload produced by agent_run.py.
"""

from __future__ import annotations

import html
from datetime import datetime

# Blue palette consistent with the gmail_cleanup report.
BLUE_DARK = "#1a3c6e"
BLUE_MID = "#2e6da4"
BLUE_LIGHT = "#dce9f7"
GREY = "#666666"
GREEN = "#1e7e34"
AMBER = "#b8860b"
RED = "#b02a37"

_VERDICT_COLOR = {"shortlist": GREEN, "maybe": AMBER, "pass": RED}


def _esc(s) -> str:
    return html.escape(str(s if s is not None else ""))


def _fit_color(score) -> str:
    try:
        s = int(score)
    except (TypeError, ValueError):
        return GREY
    return GREEN if s >= 70 else (AMBER if s >= 55 else GREY)


def _slot_label() -> str:
    h = datetime.now().hour
    return "Morning" if h < 14 else "Evening"


# ── HTML ─────────────────────────────────────────────────────────────────────
def build_html(payload: dict) -> str:
    matches = payload.get("matches", [])
    meta = payload.get("_meta", {})
    today = datetime.now().strftime("%d %b %Y")
    slot = _slot_label()
    top = [m for m in matches if (m.get("fit_score") or 0) >= 70]

    rows = []
    for m in matches:
        rows.append(_job_card_html(m))
    cards = "\n".join(rows) if rows else (
        "<p style='color:#666'>No roles met the fit threshold this run. "
        "See search notes below for which sources were reached.</p>")

    hats_legend = ("<span style='color:%s'>&#9679; shortlist</span> &nbsp; "
                   "<span style='color:%s'>&#9679; maybe</span> &nbsp; "
                   "<span style='color:%s'>&#9679; pass</span>") % (GREEN, AMBER, RED)

    return f"""\
<div style="font-family:Helvetica,Arial,sans-serif;max-width:760px;margin:auto;color:#1a1a1a">
  <div style="background:{BLUE_DARK};color:#fff;padding:18px 22px;border-radius:8px">
    <h2 style="margin:0">Job Search Report — {today} ({slot})</h2>
    <div style="color:{BLUE_LIGHT};font-size:13px;margin-top:4px">
      Senior data/AI platform leadership roles • India GCCs • last 7 days
    </div>
  </div>

  <div style="background:{BLUE_LIGHT};border-radius:8px;padding:12px 18px;margin:14px 0;
              display:flex;gap:30px;font-size:14px">
    <div><b style="font-size:20px;color:{BLUE_DARK}">{len(matches)}</b><br>roles evaluated</div>
    <div><b style="font-size:20px;color:{GREEN}">{len(top)}</b><br>strong fits (&ge;70)</div>
    <div style="font-size:12px;color:{GREY};align-self:center">
      Hats: {hats_legend}
    </div>
  </div>

  {cards}

  <div style="margin-top:18px;padding:12px 16px;background:#f5f5f5;border-radius:8px;
              font-size:12px;color:{GREY}">
    <b>Search notes:</b> {_esc(payload.get('search_notes'))}<br><br>
    Generated by the job-search agent ({_esc(meta.get('model'))}) •
    {meta.get('web_searches', 0)} web searches •
    run cost ~${meta.get('cost_usd', 0):.2f}<br>
    <i>Referral suggestions, where present, are drafts for your reference only — nothing
    is sent to anyone. Verify role status and posting dates on the company site before applying.</i>
  </div>
</div>"""


def _hats_html(hats: dict) -> str:
    if not hats:
        return ""
    parts = []
    for who, label in (("hr_director", "HR Director"),
                       ("hiring_manager", "Hiring Mgr"),
                       ("recruiter", "Recruiter")):
        h = hats.get(who) or {}
        v = (h.get("verdict") or "").lower()
        color = _VERDICT_COLOR.get(v, GREY)
        parts.append(
            f"<div style='margin:2px 0'><b>{label}:</b> "
            f"<span style='color:{color}'>{_esc(v or '—')}</span> "
            f"<span style='color:{GREY}'>— {_esc(h.get('reason'))}</span></div>")
    return "".join(parts)


def _list_html(items, color) -> str:
    if not items:
        return "<li style='color:#999'>none</li>"
    return "".join(f"<li style='color:{color};margin:2px 0'>{_esc(x)}</li>" for x in items)


def _job_card_html(m: dict) -> str:
    fit = m.get("fit_score")
    fc = _fit_color(fit)
    referral = m.get("referral")
    referral_html = ""
    if referral:
        referral_html = (
            f"<div style='margin-top:8px;padding:8px 10px;background:#fff8e1;"
            f"border-left:3px solid {AMBER};font-size:13px'>"
            f"<b>Referral angle (draft — not sent):</b> {_esc(referral.get('contact'))}"
            f"<br><i>{_esc(referral.get('message'))}</i></div>")

    posted = m.get("posted_date") or "date unconfirmed — verify on site"
    seen = f" • first seen: {_esc(m.get('first_seen'))}" if m.get("first_seen") else ""
    return f"""\
  <div style="border:1px solid #e0e0e0;border-radius:8px;padding:14px 16px;margin:10px 0">
    <table style="width:100%"><tr>
      <td style="font-size:16px"><b>{_esc(m.get('title'))}</b> — {_esc(m.get('company'))}</td>
      <td style="text-align:right;white-space:nowrap">
        <span style="background:{fc};color:#fff;border-radius:12px;padding:3px 10px;font-size:13px">
          fit {_esc(fit)}</span></td>
    </tr></table>
    <div style="color:{GREY};font-size:13px;margin:3px 0 8px">
      {_esc(m.get('location'))} • posted: {_esc(posted)}{seen} • {_esc(m.get('source'))}</div>
    <div style="font-size:13px;margin-bottom:8px">{_esc(m.get('rationale'))}</div>
    <div style="font-size:13px;margin-bottom:8px">{_hats_html(m.get('three_hats'))}</div>
    <table style="width:100%;font-size:13px"><tr style="vertical-align:top">
      <td style="width:50%"><b>Emphasize (true to resume):</b>
        <ul style="margin:4px 0;padding-left:18px">{_list_html(m.get('emphasize'), '#1a1a1a')}</ul></td>
      <td style="width:50%"><b>Gaps → learning:</b>
        <ul style="margin:4px 0;padding-left:18px">{_list_html(m.get('gaps'), AMBER)}</ul></td>
    </tr></table>
    {referral_html}
    <div style="margin-top:8px">
      <a href="{_esc(m.get('url'))}" style="color:{BLUE_MID}">View / apply &rarr;</a></div>
  </div>"""


# ── PDF ──────────────────────────────────────────────────────────────────────
def build_pdf(payload: dict, out_path) -> str:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable

    styles = getSampleStyleSheet()
    h = ParagraphStyle("h", parent=styles["Heading2"], textColor=colors.HexColor(BLUE_DARK))
    body = ParagraphStyle("b", parent=styles["BodyText"], fontSize=9, leading=13)
    small = ParagraphStyle("s", parent=styles["BodyText"], fontSize=8,
                           textColor=colors.HexColor(GREY))

    doc = SimpleDocTemplate(str(out_path), pagesize=A4,
                            topMargin=1.5 * cm, bottomMargin=1.5 * cm,
                            leftMargin=1.8 * cm, rightMargin=1.8 * cm)
    story = [Paragraph(f"Job Search Report — {datetime.now():%d %b %Y} ({_slot_label()})", h),
             Paragraph("Senior data/AI platform leadership • India GCCs • last 7 days", small),
             HRFlowable(width="100%", color=colors.HexColor(BLUE_MID)), Spacer(1, 6)]

    for m in payload.get("matches", []):
        story.append(Paragraph(
            f"<b>{_esc(m.get('title'))} — {_esc(m.get('company'))}</b> "
            f"(fit {_esc(m.get('fit_score'))})", body))
        story.append(Paragraph(
            f"{_esc(m.get('location'))} • posted: "
            f"{_esc(m.get('posted_date') or 'unconfirmed')} • {_esc(m.get('source'))}", small))
        story.append(Paragraph(_esc(m.get("rationale")), body))
        hats = m.get("three_hats") or {}
        for who, label in (("hr_director", "HR Director"), ("hiring_manager", "Hiring Mgr"),
                           ("recruiter", "Recruiter")):
            hh = hats.get(who) or {}
            story.append(Paragraph(
                f"&nbsp;&nbsp;<b>{label}:</b> {_esc(hh.get('verdict'))} — {_esc(hh.get('reason'))}", small))
        if m.get("emphasize"):
            story.append(Paragraph("<b>Emphasize:</b> " +
                                   "; ".join(_esc(x) for x in m["emphasize"]), body))
        if m.get("gaps"):
            story.append(Paragraph("<b>Gaps → learning:</b> " +
                                   "; ".join(_esc(x) for x in m["gaps"]), body))
        story.append(Paragraph(f'<a href="{_esc(m.get("url"))}">{_esc(m.get("url"))}</a>', small))
        story.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd")))
        story.append(Spacer(1, 5))

    story.append(Spacer(1, 6))
    story.append(Paragraph("Search notes: " + _esc(payload.get("search_notes")), small))
    story.append(Paragraph(
        "Referral drafts (if any) are for your reference only — nothing is sent. "
        "Verify role status on the company site before applying.", small))
    doc.build(story)
    return str(out_path)
